// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: src/proto/prod.proto

/*
Package service is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package service

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_GrpcGateWayService_GetGrpcGateWayStock_0(ctx context.Context, marshaler runtime.Marshaler, client GrpcGateWayServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GrpcGateWayRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["goods_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "goods_id")
	}

	protoReq.GoodsId, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "goods_id", err)
	}

	msg, err := client.GetGrpcGateWayStock(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GrpcGateWayService_GetGrpcGateWayStock_0(ctx context.Context, marshaler runtime.Marshaler, server GrpcGateWayServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GrpcGateWayRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["goods_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "goods_id")
	}

	protoReq.GoodsId, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "goods_id", err)
	}

	msg, err := server.GetGrpcGateWayStock(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterGrpcGateWayServiceHandlerServer registers the http handlers for service GrpcGateWayService to "mux".
// UnaryRPC     :call GrpcGateWayServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterGrpcGateWayServiceHandlerFromEndpoint instead.
func RegisterGrpcGateWayServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server GrpcGateWayServiceServer) error {

	mux.Handle("GET", pattern_GrpcGateWayService_GetGrpcGateWayStock_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/service.GrpcGateWayService/GetGrpcGateWayStock", runtime.WithHTTPPathPattern("/v1/prod/{goods_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GrpcGateWayService_GetGrpcGateWayStock_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GrpcGateWayService_GetGrpcGateWayStock_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterGrpcGateWayServiceHandlerFromEndpoint is same as RegisterGrpcGateWayServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterGrpcGateWayServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterGrpcGateWayServiceHandler(ctx, mux, conn)
}

// RegisterGrpcGateWayServiceHandler registers the http handlers for service GrpcGateWayService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterGrpcGateWayServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGrpcGateWayServiceHandlerClient(ctx, mux, NewGrpcGateWayServiceClient(conn))
}

// RegisterGrpcGateWayServiceHandlerClient registers the http handlers for service GrpcGateWayService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "GrpcGateWayServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "GrpcGateWayServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "GrpcGateWayServiceClient" to call the correct interceptors.
func RegisterGrpcGateWayServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client GrpcGateWayServiceClient) error {

	mux.Handle("GET", pattern_GrpcGateWayService_GetGrpcGateWayStock_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/service.GrpcGateWayService/GetGrpcGateWayStock", runtime.WithHTTPPathPattern("/v1/prod/{goods_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GrpcGateWayService_GetGrpcGateWayStock_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GrpcGateWayService_GetGrpcGateWayStock_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_GrpcGateWayService_GetGrpcGateWayStock_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "prod", "goods_id"}, ""))
)

var (
	forward_GrpcGateWayService_GetGrpcGateWayStock_0 = runtime.ForwardResponseMessage
)
