// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: src/proto/prod.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcGateWayServiceClient is the client API for GrpcGateWayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcGateWayServiceClient interface {
	GetGrpcGateWayStock(ctx context.Context, in *GrpcGateWayRequest, opts ...grpc.CallOption) (*GrpcGateWayResponse, error)
}

type grpcGateWayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcGateWayServiceClient(cc grpc.ClientConnInterface) GrpcGateWayServiceClient {
	return &grpcGateWayServiceClient{cc}
}

func (c *grpcGateWayServiceClient) GetGrpcGateWayStock(ctx context.Context, in *GrpcGateWayRequest, opts ...grpc.CallOption) (*GrpcGateWayResponse, error) {
	out := new(GrpcGateWayResponse)
	err := c.cc.Invoke(ctx, "/service.GrpcGateWayService/GetGrpcGateWayStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcGateWayServiceServer is the server API for GrpcGateWayService service.
// All implementations must embed UnimplementedGrpcGateWayServiceServer
// for forward compatibility
type GrpcGateWayServiceServer interface {
	GetGrpcGateWayStock(context.Context, *GrpcGateWayRequest) (*GrpcGateWayResponse, error)
	mustEmbedUnimplementedGrpcGateWayServiceServer()
}

// UnimplementedGrpcGateWayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcGateWayServiceServer struct {
}

func (UnimplementedGrpcGateWayServiceServer) GetGrpcGateWayStock(context.Context, *GrpcGateWayRequest) (*GrpcGateWayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrpcGateWayStock not implemented")
}
func (UnimplementedGrpcGateWayServiceServer) mustEmbedUnimplementedGrpcGateWayServiceServer() {}

// UnsafeGrpcGateWayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcGateWayServiceServer will
// result in compilation errors.
type UnsafeGrpcGateWayServiceServer interface {
	mustEmbedUnimplementedGrpcGateWayServiceServer()
}

func RegisterGrpcGateWayServiceServer(s grpc.ServiceRegistrar, srv GrpcGateWayServiceServer) {
	s.RegisterService(&GrpcGateWayService_ServiceDesc, srv)
}

func _GrpcGateWayService_GetGrpcGateWayStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcGateWayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcGateWayServiceServer).GetGrpcGateWayStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.GrpcGateWayService/GetGrpcGateWayStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcGateWayServiceServer).GetGrpcGateWayStock(ctx, req.(*GrpcGateWayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcGateWayService_ServiceDesc is the grpc.ServiceDesc for GrpcGateWayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcGateWayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.GrpcGateWayService",
	HandlerType: (*GrpcGateWayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGrpcGateWayStock",
			Handler:    _GrpcGateWayService_GetGrpcGateWayStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/prod.proto",
}
